/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// int putchar(int c);
// int printf(const char *format, ...);
// int atoi(const char *nptr);
// int __fastcall __isoc99_scanf(_QWORD, _QWORD); weak
// int _gmon_start__(void); weak
// int __fastcall _cxa_finalize(_QWORD); weak
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
__int64 __fastcall merge(__int64 a1, int a2, int a3, int a4);
__int64 __fastcall sort(__int64 a1, int a2, int a3);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();
// int ITM_deregisterTMCloneTable(void); weak
// int Jv_RegisterClasses(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_EB4; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
_UNKNOWN _JCR_LIST__; // weak
void *_dso_handle = &_dso_handle; // weak
char _bss_start; // weak
_UNKNOWN unk_20205F; // weak
// extern _UNKNOWN __cxa_finalize; weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000000006F0) ----------------------------------------------------
int init_proc()
{
  void *v0; // rax@1

  v0 = &__gmon_start__;
  if ( &__gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 780: using guessed type int _gmon_start__(void);

//----- (0000000000000790) ----------------------------------------------------
#error "796: positive sp value has been found (funcsize=3)"

//----- (00000000000007C0) ----------------------------------------------------
int deregister_tm_clones()
{
  int (**v0)(void); // rax@1

  v0 = (int (**)(void))(&unk_20205F - (_UNKNOWN *)&_bss_start);
  if ( (unsigned __int64)(&unk_20205F - (_UNKNOWN *)&_bss_start) > 0xE )
  {
    v0 = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      LODWORD(v0) = ITM_deregisterTMCloneTable();
  }
  return (unsigned __int64)v0;
}
// 202058: using guessed type char _bss_start;
// 202098: using guessed type int ITM_deregisterTMCloneTable(void);

//----- (0000000000000800) ----------------------------------------------------
int register_tm_clones()
{
  return 0;
}

//----- (0000000000000850) ----------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax@4

  if ( !_bss_start )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 788: using guessed type int __fastcall _cxa_finalize(_QWORD);
// 202050: using guessed type void *_dso_handle;
// 202058: using guessed type char _bss_start;

//----- (0000000000000890) ----------------------------------------------------
int frame_dummy()
{
  int result; // eax@2

  if ( _JCR_LIST__ && &Jv_RegisterClasses )
  {
    Jv_RegisterClasses();
    result = register_tm_clones();
  }
  else
  {
    result = register_tm_clones();
  }
  return result;
}
// 2020A0: using guessed type int Jv_RegisterClasses(void);

//----- (00000000000008C0) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v3; // eax@1
  signed __int64 v4; // rax@1
  void *v5; // rsp@3
  int result; // eax@9
  __int64 v7; // rbx@9
  __int64 v8; // [sp+1000h] [bp-1048h]@2
  const char **v9; // [sp+1FE8h] [bp-60h]@1
  int v10; // [sp+1FF4h] [bp-54h]@1
  int i; // [sp+1FF8h] [bp-50h]@3
  int v12; // [sp+1FFCh] [bp-4Ch]@1
  __int64 v13; // [sp+2000h] [bp-48h]@1
  __int64 v14; // [sp+2008h] [bp-40h]@3
  __int64 v15; // [sp+2010h] [bp-38h]@1
  __int64 v16; // [sp+2020h] [bp-28h]@3

  v10 = argc;
  v9 = argv;
  v15 = *MK_FP(__FS__, 40LL);
  v3 = atoi(argv[1]);
  v12 = v3;
  v13 = v3 - 1LL;
  v4 = 16 * ((4LL * v3 + 18) / 0x10uLL);
  while ( &v8 != &v8 )
    ;
  v5 = alloca(v4);
  v14 = 4 * (((unsigned __int64)&v16 + 3) >> 2);
  for ( i = 0; i < v12; ++i )
    __isoc99_scanf(&unk_EB4, 4LL * i + v14);
  sort(v14, 0, v12 - 1);
  for ( i = 0; i < v12; ++i )
    printf("%d ", *(_DWORD *)(v14 + 4LL * i));
  putchar(10);
  result = 0;
  v7 = *MK_FP(__FS__, 40LL) ^ v15;
  return result;
}
// 770: using guessed type int __fastcall __isoc99_scanf(_QWORD, _QWORD);

//----- (0000000000000A6E) ----------------------------------------------------
__int64 __fastcall merge(__int64 a1, int a2, int a3, int a4)
{
  void *v4; // rsp@3
  void *v5; // rsp@5
  __int64 v7; // [sp+1000h] [bp-1040h]@2
  int v8; // [sp+1FCCh] [bp-74h]@1
  int v9; // [sp+1FD0h] [bp-70h]@1
  int v10; // [sp+1FD4h] [bp-6Ch]@1
  __int64 v11; // [sp+1FD8h] [bp-68h]@1
  int i; // [sp+1FE4h] [bp-5Ch]@5
  int j; // [sp+1FE8h] [bp-58h]@8
  int v14; // [sp+1FECh] [bp-54h]@11
  int v15; // [sp+1FF0h] [bp-50h]@1
  int v16; // [sp+1FF4h] [bp-4Ch]@1
  __int64 v17; // [sp+1FF8h] [bp-48h]@1
  unsigned __int64 v18; // [sp+2000h] [bp-40h]@3
  __int64 v19; // [sp+2008h] [bp-38h]@3
  unsigned __int64 v20; // [sp+2010h] [bp-30h]@5
  __int64 v21; // [sp+2018h] [bp-28h]@1
  __int64 v22; // [sp+2020h] [bp-20h]@3

  v11 = a1;
  v10 = a2;
  v9 = a3;
  v8 = a4;
  v21 = *MK_FP(__FS__, 40LL);
  v15 = a3 - a2 + 1;
  v16 = a4 - a3;
  v17 = v15 - 1LL;
  while ( &v7 != &v7 )
    ;
  v4 = alloca(16 * ((4LL * (a3 - a2 + 1) + 18) / 0x10uLL));
  v18 = 4 * (((unsigned __int64)&v22 + 3) >> 2);
  v19 = v16 - 1LL;
  while ( &v7 != &v7 )
    ;
  v5 = alloca(16 * ((4LL * v16 + 18) / 0x10uLL));
  v20 = 4 * (((unsigned __int64)&v22 + 3) >> 2);
  for ( i = 0; i < v15; ++i )
    *(_DWORD *)(v18 + 4LL * i) = *(_DWORD *)(4LL * (v10 + i) + v11);
  for ( j = 0; j < v16; ++j )
    *(_DWORD *)(v20 + 4LL * j) = *(_DWORD *)(4 * (v9 + j + 1LL) + v11);
  i = 0;
  j = 0;
  v14 = v10;
  while ( i < v15 && j < v16 )
  {
    if ( *(_DWORD *)(v18 + 4LL * i) >= *(_DWORD *)(v20 + 4LL * j) )
      *(_DWORD *)(4LL * v14 + v11) = *(_DWORD *)(v20 + 4LL * j++);
    else
      *(_DWORD *)(4LL * v14 + v11) = *(_DWORD *)(v18 + 4LL * i++);
    ++v14;
  }
  while ( i < v15 )
    *(_DWORD *)(4LL * v14++ + v11) = *(_DWORD *)(v18 + 4LL * i++);
  while ( j < v16 )
    *(_DWORD *)(4LL * v14++ + v11) = *(_DWORD *)(v20 + 4LL * j++);
  return *MK_FP(__FS__, 40LL) ^ v21;
}

//----- (0000000000000DAC) ----------------------------------------------------
__int64 __fastcall sort(__int64 a1, int a2, int a3)
{
  __int64 result; // rax@1
  int v4; // ST103C_4@2
  int v5; // [sp+1020h] [bp-20h]@1

  v5 = a3;
  result = (unsigned int)a2;
  if ( a2 < a3 )
  {
    v4 = (a2 + a3) / 2;
    sort(a1, (unsigned int)a2, (unsigned int)v4);
    sort(a1, (unsigned int)(v4 + 1), (unsigned int)v5);
    result = merge(a1, a2, v4, v5);
  }
  return result;
}

//----- (0000000000000E30) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  signed __int64 v4; // rbp@1
  __int64 v5; // rbx@2

  v3 = a3;
  v4 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v5++])(a1, a2, v3);
    while ( v5 != v4 );
  }
}
// 201DE0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 201DE8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000000EA4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
